#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd using the while loop and IFS.

while IFS=':' read -r username password userid groupid userdesc homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. User ID's place is protected by the passcode $password, more info about the user here: $userdesc"
done < /etc/passwd

