#!/usr/bin/env bash
# This script demonstrates loop iterations with conditional statements

#Loop from 1 to 10 with special cases for the 4th and 8th iterations
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
        echo "bad luck"
    elif [ $counter -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi

    counter=$((counter + 1))
done

