#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and shows custom messages for specific iterations.

counter=1

while [ "$counter" -le 20 ]; do
    case $counter in
        5)
            echo "bad luck from China"
            ;;
	    echo "$counter"
        10)
            echo "bad luck from Japan"
            ;;
	    echo "$counter"
        18)
            echo "bad luck from Italy"
            ;;
        *)
            echo "$counter"
            ;;
    esac

    counter=$((counter + 1))
done

