#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

hour=0
while [ $hour -lt 13 ]; do
    minute=1
    while [ $minute -lt 60 ]; do
        printf "%02d:%02d\n" $hour $minute
        minute=$((minute + 1))
    done
    hour=$((hour + 1))
done | head -n 70

