#!/usr/bin/env bash
# This script displays the content of the current directory in a list format,
# showing only the part of the name after the first dash.

for file in *; do
  if [[ -f "$file" && ! "$file" =~ ^\.[^.]+$ ]]; then
    filename=$(echo "$file" | cut -d '-' -f 2-)
    echo "$filename"
  fi
done

