#!/usr/bin/env bash
#a Bash script that displays a list of currently running processes.
printf "%-8s %-5s %-5s %-5s %-5s %-5s %-8s %-5s %-8s %s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "COMMAND"

# Get the list of processes
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,comm --forest --no-headers | awk '{ printf "%-8s %-5s %-5s %-5s %-5s %-5s %-8s %-5s %-8s %s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10 }'
