#!/usr/bin/env bash
# This script displays the PID and process name of processes
# whose name contains the word "bash".

current_pid=$$
current_name=$(basename "$0")

for pid in /proc/[0-9]*/cmdline; do
    if grep -q "bash" "$pid" && ! grep -q "$current_pid $current_name" "$pid"; then
        process_name=$(tr -d '\0' < "$pid")
        pid=$(basename "$(dirname "$pid")")
        echo "PID: $pid, Process Name: $process_name"
    fi
done
