#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the process ID (PID) of 4-to_infinity_and_beyond
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$pid" ]; then
  # Terminate the process
  kill "$pid"
  echo "Terminated"
else
  echo "Process not found"
fi

