#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Terminate the 4-to_infinity_and_beyond process
pkill -f "4-to_infinity_and_beyond"

# Check the exit status of the pkill command
if [ $? -eq 0 ]; then
  echo "Terminated"
else
  echo "Process not found"
fi
