#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process

# Find the process ID (PID) of the "4-to_infinity_and_beyond" process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -z "$pid" ]; then
  echo "4-to_infinity_and_beyond process is not running."
else
  # Terminate the process using the PID
  kill "$pid"
fi

