#!/usr/bin/env bash
# This script kills the process named "7-highlander"

# Find the process ID (PID) of "7-highlander"
pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [[ -n $pid ]]; then
  # Kill the process
  kill "$pid"
  echo "Process '7-highlander' has been killed."
else
  echo "Process '7-highlander' is not running."
fi

